name: hajeej
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.8
  device_preview: ^0.2.6
  shared_preferences: ^0.5.6+1
  flutter_html: ^0.11.1
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  font_awesome_flutter: ^8.7.0
  material_segmented_control: ^2.0.4



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/icons/
  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/Cairo-Regular.ttf
         weight: 400


